### ISSUE TITLE
[Request] 1.20.1

### ISSUE THREAD

**Issue by WhyAreLess** [Raxdiam/ToastBegone#3]
Would it be possible for a 1.20.1 version of ToastBegone? 

This is one mod I miss very much in Fabric as I used Toast Control (Forge) a lot!

**Comment by Raxdiam** [comment]
e41469c

Backport of ToastBegone for Fabric 1.20.1 should now be [available on Modrinth](https://modrinth.com/mod/toastbegone/version/pGaO8BoI)

**Comment by Raxdiam** [comment]
Version 1.2.0 for Minecraft 1.20(.1) is now on Modrinth
